### PR TITLE
Automatic publish to PyPI

### LINKED ISSUE #171: Add automatization to deploy repo on PyPI

### PR DESCRIPTION
**Pull request by Illumaria**
Closes #171.

### CODE REVIEW

**Comment by AlekseySh** [comment]
@Illumaria Hey, if we gonna run this workflow on an already merged commit, does it mean that we should ignore other workflows because they already worked when we merged that commit?

**Comment by Illumaria** [comment]
> @Illumaria Hey, if we gonna run this workflow on an already merged commit, does it mean that we should ignore other workflows because they already worked when we merged that commit?

In the way that is implemented in the current PR - yes, the workflow will only take into account the tag pushing event. It won't wait or check for test workflow results.

Let's go through the most common scenarios once again to see if we want to add something to the current configuration.

**Scenario №1 (suggested):**
1. Someone works on a feature/fix on a separate branch.
2. When it's finished, the author creates a PR, and test workflows are triggered by `on: pull_request` event.
3. You, of course, won't merge that PR until all checks are green. When they are, the PR is merged.
4. The merge commit on the `main` branch triggers test workflows (on the `main` branch) once again by `on: push` event.
5. Now, there are two very similar ways to follow:
    - You want to be 100% sure that the current `main` branch is absolutely safe to publish, so you *wait* until all the test workflows finish, *then* tag the `main` `HEAD` and push that tag, e.g.
      ```commandline
      git switch main
      git tag -a release.0.3.4 -m "release.0.3.4"
      git push origin release.0.3.4
      ```
    - You are fine with just the PR tests, so you don't wait for merge commit workflows to finish and tag the commit right away.

**Scenario №2:**
Steps 1-4 are the same as for Scenario №1.
5. You want to be 100% sure that the current `main` branch is absolutely safe to publish, so you want to wait until all the test workflows finish, but you still want to *automate the publishing* (make publishing workflow trigger automatically after tests are green). This can be done, but the latter would require you to *already* (without waiting for the workflows to finish) create and push a tag, which is equivalent to you *already* trusting that commit to be safe. Because if the tests fail for some reason, you'll have to remove the tag (which is generally a bad practice) and start the scenario all over again. So what you would probably need in this scenario is something like automatic conditional tagging (`if tests are green` -> `tag this commit` -> `run publishing workflow`), but I am not aware of a possibility of this option.

**Comment by Illumaria** [comment]
@AlekseySh I don't know if it is better to write this here or in the issue discussion. 😅

After digging into the automated tagging topic, I came up with the following config:
```yaml
name: Publish to PyPI

on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed
    branches:
      - main

jobs:
  autotag:
    name: Create tag if the commit has new version implemented
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      tagcreated: ${{ steps.autotag.outputs.tagcreated }}
    steps:
      - uses: actions/checkout@v3

      - name: Autotag
        id: autotag
        uses: butlerlogic/action-autotag@1.1.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          strategy: regex
          root: "oml/__init__.py"
          regex_pattern: >
            ^__version__ = ['"]([^'"]*)['"]
          tag_prefix: "release."

  build_and_publish_to_pypi:
    name: Build and publish Python distribution to PyPI
    needs: autotag
    if: ${{ needs.autotag.outputs.tagcreated == 'yes' }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8.0"

    - name: Build a binary wheel
      run: |
        make build_wheel

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
```
I'll break it down for you, so you could tell if this one is more convenient for the OML project.

1. The workflow is being triggered after `Tests` workflow is completed for the `main` branch. This is achieved by
    ```yaml
    on:
      workflow_run:
        workflows:
          - Tests
        types:
          - completed
        branches:
          - main
    ```
    and
    ```yaml
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    ```
2. If tests are green, `autotag` job starts. What it does is:
    - extract project version from `oml/__init__.py`;
    - prepend it with `tag_prefix: "release."`;
    - create and push that tag if it doesn't exist.
3. `build_and_publish_to_pypi` job waits for `autotag` to finish, and, if the tag was really created (pretty much equals to `new version specified in __init__.py`)
    ```yaml
    if: ${{ needs.autotag.outputs.tagcreated == 'yes' }}
    ```
    publishes the current `main` branch to PyPI.

**Comment by AlekseySh** [comment]
Hey, @Illumaria, thank you for your detailed research, I do appreciate it.
I really like the solution with auto-tagging.

Just want to double check, that I got it correctly: 
0. I think that it's time to release the repo.
1. I go to the main branch and change the version.
2. I push this commit (without any tagging).
...
rest is performed automatically: 
- commit will be tagged automatically because the version has been changed
- if all of the tests are green, we publish the repo to PyPI

**Comment by AlekseySh** [comment]
Few questions:
1. Have you tested your config with the test repo?
2. If I changed `__init__.py` in another branch and made a PR, what happens when? (My assumption is that nothing happens with PyPI until we merge that branch, and after we merged it and the tests are green it will be published to PyPI)

**Comment by Illumaria** [comment]
> Hey, @Illumaria, thank you for your detailed research, I do appreciate it. I really like the solution with auto-tagging.
> 
> Just want to double check, that I got it correctly:
> 0. I think that it's time to release the repo.
> 
> 1. I go to the main branch and change the version.
> 
> 2. I push this commit (without any tagging).
> 
> 
> ...
> 
> rest is performed automatically: 3. commit will be tagged automatically because the version has been changed 4. if all of the tests are green, we publish the repo to PyPI

Correct.

> Few questions:
> 
> 1. Have you tested your config with the test repo?
> 
> 2. If I changed `__init__.py` in another branch and made a PR, what happens when? (My assumption is that nothing happens with PyPI until we merge that branch, and after we merged it and the tests are green it will be published to PyPI)

1. Yes, I did. You can take a look at the results [here](https://github.com/Illumaria/open-metric-learning/actions/runs/3584123466/attempts/1) (failed, because I don't have permissions to push to the main OML PyPI, but I tested the same config for Test PyPI previously and it worked fine) and [here](https://github.com/Illumaria/open-metric-learning/actions/runs/3584123466) (skipped, because the tag already exists).
2. Your assumption is absolutely correct. The publishing workflow will only be triggered by events on the `main` branch, that is, when a PR is merged and a merge commit is created. The latter is formally equivalent to pushing directly to the main branch. I tested PRs as well:
image
    - the bottom three checks are tests for the PR;
    - next, the same checks for the `main` branch;
    - finally, on the top, publishing workflow (which, in fact, was not implemented correctly at the time of that run, but still correct enough to be triggered by the right event).

**Comment by AlekseySh** [comment]
@Illumaria Thank you for the explanations and the examples! This way of publishing seems very convenient to me.

Please, push your config to this PR.

**Comment by AlekseySh** [comment]
@Illumaria thank you for the great contribution! You've really simplified my life. I gonna release the project soon, so, I'll test the workflow in action. If something is wrong I will let you know.

**Review by AlekseySh — APPROVED** [review]
cool!

**Pull request merged**
